# Generated by Django 5.2.2 on 2025-06-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_groups_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active."
                "Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
