# Generated by Django 5.2.1 on 2025-06-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активно"),
                    ("cancelled", "Отменено"),
                    ("completed", "Завершено"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
