# Generated by Django 5.2.1 on 2025-06-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "permissions": [
                    ("can_reserve", "Can make a reservation"),
                    ("can_view_all_bookings", "Can view all bookings"),
                    ("can_change_reservation", "Can change any reservation"),
                    ("can_delete_any_booking", "Can delete any booking"),
                    ("can_cancel_booking", "Can cancel booking"),
                ],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
    ]
