# Generated by Django 5.2.1 on 2025-06-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_booking_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
    ]
