# Generated by Django 5.2.2 on 2025-06-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0004_booking_reminder_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="Напоминание отправлено"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("active", "Активно"), ("cancelled", "Отменено"), ("completed", "Завершено")],
                default="active",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
