# Generated by Django 5.2.2 on 2025-06-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0005_alter_booking_reminder_sent_alter_booking_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["date", "time"],
                "permissions": [
                    ("can_reserve", "Может создавать бронь"),
                    ("can_view_all_bookings", "Может просматривать все брони"),
                    ("can_change_reservation", "Может изменять брони"),
                    ("can_delete_any_booking", "Может удалять любые брони"),
                    ("can_cancel_booking", "Может отменять брони"),
                ],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
    ]
