# Generated by Django 5.2.2 on 2025-06-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_alter_booking_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "permissions": [
                    ("can_reserve", "Can make a reservation"),
                    ("can_view_all_bookings", "Can view all bookings"),
                    ("can_change_reservation", "Can change any reservation"),
                    ("can_delete_any_booking", "Can delete any booking"),
                    ("can_cancel_booking", "Can cancel booking"),
                ],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("active", "Активно"), ("cancelled", "Отменено"), ("completed", "Завершено")],
                default="active",
                max_length=20,
            ),
        ),
    ]
