# Generated by Django 5.2.2 on 2025-06-12 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_alter_booking_options_alter_booking_reminder_sent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="Напоминание отправлено"),
        ),
    ]
