# Generated by Django 5.2.2 on 2025-06-12 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0008_alter_booking_reminder_sent"),
        ("tables", "0006_alter_table_options_alter_table_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["date", "time"],
                "permissions": [
                    ("can_reserve", "Can make a reservation"),
                    ("can_view_all_bookings", "Can view all bookings"),
                    ("can_change_reservation", "Can change any reservation"),
                    ("can_delete_any_booking", "Can delete any booking"),
                    ("can_cancel_booking", "Can cancel booking"),
                ],
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
            },
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(verbose_name="Booking date"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="duration",
            field=models.PositiveIntegerField(default=1, verbose_name="Duration (hours)"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="person_count",
            field=models.PositiveIntegerField(default=1, verbose_name="Number of persons"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="Reminder sent"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("cancelled", "Cancelled"),
                    ("completed", "Completed"),
                    ("processing", "Processing"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.table", verbose_name="Table"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="time",
            field=models.TimeField(verbose_name="Booking time"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User"
            ),
        ),
    ]
