# Generated by Django 5.2.2 on 2025-06-12 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0009_alter_booking_options_alter_booking_unique_together_and_more"),
        ("tables", "0007_alter_table_options_alter_table_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["date", "time"],
                "permissions": [
                    ("can_reserve", "Может создавать бронь"),
                    ("can_view_all_bookings", "Может просматривать все брони"),
                    ("can_change_reservation", "Может изменять любую бронь"),
                    ("can_delete_any_booking", "Может удалять любую бронь"),
                    ("can_cancel_booking", "Может отменять бронь"),
                ],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="date",
            field=models.DateField(verbose_name="Дата бронирования"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="duration",
            field=models.PositiveIntegerField(
                default=1, help_text="Продолжительность бронирования в часах", verbose_name="Длительность (часы)"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="person_count",
            field=models.PositiveIntegerField(default=1, verbose_name="Количество персон"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="Напоминание отправлено"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активно"),
                    ("cancelled", "Отменено"),
                    ("completed", "Завершено"),
                    ("processing", "В обработке"),
                ],
                default="active",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="table",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tables.table", verbose_name="Столик"
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="time",
            field=models.TimeField(verbose_name="Время бронирования"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="Пользователь"
            ),
        ),
    ]
