# Generated by Django 5.2.2 on 2025-06-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0010_alter_booking_options_alter_booking_created_at_and_more"),
        ("tables", "0008_alter_table_options_alter_table_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booking",
            options={
                "permissions": [
                    ("can_reserve", "Can make a reservation"),
                    ("can_view_all_bookings", "Can view all bookings"),
                    ("can_change_reservation", "Can change any reservation"),
                    ("can_delete_any_booking", "Can delete any booking"),
                    ("can_cancel_booking", "Can cancel booking"),
                ],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.AlterField(
            model_name="booking",
            name="duration",
            field=models.PositiveIntegerField(default=1, verbose_name="Длительность (часов)"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Активно"), ("cancelled", "Отменено"), ("completed", "Завершено")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("table", "date", "time")},
        ),
    ]
