# Generated by Django 5.2.2 on 2025-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0011_alter_booking_options_alter_booking_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Активно"), ("CANCELLED", "Отменено"), ("COMPLETED", "Завершено")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
