# Generated by Django 5.2.2 on 2025-06-13 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0012_alter_booking_status"),
        ("tables", "0008_alter_table_options_alter_table_description_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("table", "date")},
        ),
    ]
