# Generated by Django 5.2.2 on 2025-06-13 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0013_alter_booking_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together=set(),
        ),
    ]
