# Generated by Django 5.2.1 on 2025-06-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название столика"),
                ),
                ("description", models.TextField(verbose_name="Описание столика")),
                ("numbers", models.PositiveIntegerField(verbose_name="Номер столика")),
                (
                    "number_of_seats",
                    models.PositiveIntegerField(verbose_name="Количество посадочных мест"),
                ),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="Место расположение"),
                ),
                (
                    "picture",
                    models.ImageField(upload_to="tables/", verbose_name="Фото столика"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "is_available",
                    models.BooleanField(default=False, verbose_name="Свободен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
            },
        ),
    ]
