# Generated by Django 5.2.1 on 2025-06-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="Свободен"),
        ),
        migrations.AlterField(
            model_name="table",
            name="numbers",
            field=models.PositiveIntegerField(unique=True, verbose_name="Номер столика"),
        ),
    ]
