# Generated by Django 5.2.1 on 2025-06-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0002_alter_table_is_available_alter_table_numbers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={
                "ordering": ["numbers"],
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
            },
        ),
    ]
