# Generated by Django 5.2.1 on 2025-06-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0003_alter_table_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={
                "ordering": ["numbers"],
                "permissions": [
                    ("can_reserve", "Может создавать бронь"),
                    ("can_cancel_reservation", "Может отменять бронь"),
                    ("can_change_reservation", "Может изменять бронь"),
                ],
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
            },
        ),
    ]
