# Generated by Django 5.2.2 on 2025-06-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0004_alter_table_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="is_available",
        ),
    ]
