# Generated by Django 5.2.2 on 2025-06-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0005_remove_table_is_available"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={
                "ordering": ["numbers"],
                "permissions": [
                    ("can_reserve", "Can make a reservation"),
                    ("can_cancel_reservation", "Can cancel reservation"),
                    ("can_change_reservation", "Can change reservation"),
                ],
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
            },
        ),
        migrations.AlterField(
            model_name="table",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="table",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="table",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Active"),
        ),
        migrations.AlterField(
            model_name="table",
            name="location",
            field=models.CharField(max_length=100, verbose_name="Location"),
        ),
        migrations.AlterField(
            model_name="table",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Table name"),
        ),
        migrations.AlterField(
            model_name="table",
            name="number_of_seats",
            field=models.PositiveIntegerField(verbose_name="Number of seats"),
        ),
        migrations.AlterField(
            model_name="table",
            name="numbers",
            field=models.PositiveIntegerField(unique=True, verbose_name="Table number"),
        ),
        migrations.AlterField(
            model_name="table",
            name="picture",
            field=models.ImageField(upload_to="tables/", verbose_name="Photo"),
        ),
        migrations.AlterField(
            model_name="table",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated at"),
        ),
    ]
