# Generated by Django 5.2.2 on 2025-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0006_alter_table_options_alter_table_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={
                "ordering": ["numbers"],
                "permissions": [
                    ("can_reserve", "Может бронировать"),
                    ("can_cancel_reservation", "Может отменять брони"),
                    ("can_change_reservation", "Может изменять брони"),
                ],
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
            },
        ),
        migrations.AlterField(
            model_name="table",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="table",
            name="description",
            field=models.TextField(verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="table",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="table",
            name="location",
            field=models.CharField(max_length=100, verbose_name="Расположение"),
        ),
        migrations.AlterField(
            model_name="table",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название столика"),
        ),
        migrations.AlterField(
            model_name="table",
            name="number_of_seats",
            field=models.PositiveIntegerField(verbose_name="Количество мест"),
        ),
        migrations.AlterField(
            model_name="table",
            name="numbers",
            field=models.PositiveIntegerField(unique=True, verbose_name="Номер столика"),
        ),
        migrations.AlterField(
            model_name="table",
            name="picture",
            field=models.ImageField(upload_to="tables/", verbose_name="Фотография"),
        ),
        migrations.AlterField(
            model_name="table",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
    ]
