# Generated by Django 5.2.2 on 2025-06-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0007_alter_table_options_alter_table_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="table",
            options={
                "ordering": ["numbers"],
                "permissions": [
                    ("can_reserve", "Может создавать бронь"),
                    ("can_cancel_reservation", "Может отменять бронь"),
                    ("can_change_reservation", "Может изменять бронь"),
                ],
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
            },
        ),
        migrations.AlterField(
            model_name="table",
            name="description",
            field=models.TextField(verbose_name="Описание столика"),
        ),
        migrations.AlterField(
            model_name="table",
            name="location",
            field=models.CharField(max_length=100, verbose_name="Место расположение"),
        ),
        migrations.AlterField(
            model_name="table",
            name="number_of_seats",
            field=models.PositiveIntegerField(verbose_name="Количество посадочных мест"),
        ),
        migrations.AlterField(
            model_name="table",
            name="picture",
            field=models.ImageField(upload_to="tables/", verbose_name="Фото столика"),
        ),
    ]
