# Generated by Django 5.2.1 on 2025-06-03 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="employee/"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="ФИО сотрудника"),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="Дата рождения сотрудника"),
                ),
                (
                    "post",
                    models.CharField(max_length=100, verbose_name="Должность сотрудника"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание должностных обязанностей сотрудника"),
                ),
                (
                    "getting_started",
                    models.DateField(verbose_name="Начало работы в этой должности"),
                ),
                (
                    "getting_started_in_restaurant",
                    models.DateField(verbose_name="Начало работы в ресторане"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания карточки"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата изменения карточки"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сотрудник",
                "verbose_name_plural": "Сотрудники",
            },
        ),
    ]
