# Generated by Django 5.2.2 on 2025-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="employee/", verbose_name="Фотография сотрудника"
            ),
        ),
    ]
