# Generated by Django 5.2.1 on 2025-06-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Наименование услуги"),
        ),
    ]
