# Generated by Django 5.2.1 on 2025-06-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_attendance_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="attendance",
                verbose_name="Изображение",
            ),
        ),
    ]
