# Generated by Django 5.2.1 on 2025-06-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_alter_attendance_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendance",
            options={
                "permissions": [
                    ("can_add_attendance", "Может добавлять услуги"),
                    ("can_change_attendance", "Может изменять услуги"),
                    ("can_delete_attendance", "Может удалять услуги"),
                ],
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
